-- Phase 3: moderated public guestbook.
-- Run this in the Supabase SQL editor after visitor_tracking.sql.

create table if not exists public.guestbook_entries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 80),
  message text not null check (char_length(message) between 8 and 500),
  role text not null default '',
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  visitor_hash text not null default '',
  moderated_at timestamptz,
  moderated_by text,
  created_at timestamptz not null default now()
);

create index if not exists guestbook_status_created_at_idx
  on public.guestbook_entries (status, created_at desc);

alter table public.guestbook_entries enable row level security;

-- The Express API uses the Supabase service role, so these policies are
-- intentionally restrictive for direct browser/anon access.
drop policy if exists "Guestbook entries are private" on public.guestbook_entries;
create policy "Guestbook entries are private"
  on public.guestbook_entries for all
  using (false)
  with check (false);
