create table if not exists public.product_reactions (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.content(id) on delete cascade,
  reaction text not null default 'love',
  visitor_hash text not null,
  created_at timestamptz not null default now(),
  unique (product_id, visitor_hash)
);

alter table public.product_reactions
  add column if not exists reaction text not null default 'love';

create index if not exists product_reactions_product_id_idx
  on public.product_reactions(product_id);
