create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  visitor_hash text not null,
  user_agent text not null default '',
  referrer text not null default '',
  page text not null default '/',
  visited_at timestamptz not null default now()
);

create index if not exists visitor_events_visited_at_idx
  on public.visitor_events (visited_at desc);

alter table public.visitor_events enable row level security;
